name: waiterr
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  badges: ^3.1.2
  intl: ^0.18.1
  cached_network_image: ^3.2.2
  connectivity_plus: ^4.0.2
#  expandable_group: ^0.0.8
  firebase_auth: ^4.1.3
  flutter_mobx: ^2.0.6+5
  flutter_rating_bar: ^4.0.1
  google_fonts: ^5.1.0
  image_picker: ^1.0.4
  firebase_core: ^2.3.0
  mobx: ^2.1.3
  otp_text_field: ^1.1.3
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  sms_autofill: ^2.2.0
  url_launcher: ^6.1.6
  device_info_plus: ^9.0.3
  firebase_database: ^10.0.6
  google_sign_in: ^6.1.5
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/img/
