name: waiterr
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  badges: ^3.1.2
  intl: ^0.19.0
  cached_network_image: ^3.2.2
  connectivity_plus: ^6.1.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4
  flutter_mobx: ^2.0.6+5
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.2.1
  image_picker: ^1.0.4
  firebase_core: ^3.6.0
  mobx: ^2.1.3
  otp_text_field: ^1.1.3
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  sms_autofill: ^2.2.0
  url_launcher: ^6.1.6
  device_info_plus: ^11.1.0
  firebase_database: ^11.1.4
  google_sign_in: ^6.1.5
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  barcode_scan2: ^4.3.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # Fonts
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf

    - family: Dancing
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
          weight: 400
        - asset: assets/fonts/DancingScript-Medium.ttf
          weight: 600
        - asset: assets/fonts/DancingScript-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/DancingScript-Bold.ttf
          weight: 800


  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/img/
