name: waiterr
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  badges: ^2.0.2
  intl: ^0.17.0
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.5
  expandable_group: ^0.0.8
  firebase_auth: ^3.3.19
  flutter_mobx: ^2.0.6+1
  flutter_rating_bar: ^4.0.1
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  mobx: ^2.0.7+2
  otp_text_field: ^1.1.3
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  sms_autofill: ^2.2.0
  url_launcher: ^6.1.4
  device_info_plus: ^3.2.3
  cloud_firestore: ^3.1.18
  firebase_database: ^9.0.16
  google_sign_in: ^5.3.3
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.1.0
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/img/
